<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="" tests="1" assertions="0" errors="1" warnings="0" failures="0" skipped="0" time="3.418708">
    <testsuite name="Feature" tests="1" assertions="0" errors="1" warnings="0" failures="0" skipped="0" time="3.418708">
      <testsuite name="Tests\Feature\ProdutoTest" file="/home/vagrant/tdd/tests/Feature/ProdutoTest.php" tests="1" assertions="0" errors="1" warnings="0" failures="0" skipped="0" time="3.418708">
        <testcase name="um_produto_pode_ser_criado" class="Tests\Feature\ProdutoTest" classname="Tests.Feature.ProdutoTest" file="/home/vagrant/tdd/tests/Feature/ProdutoTest.php" line="18" assertions="0" time="3.418708">
          <error type="Symfony\Component\HttpKernel\Exception\NotFoundHttpException">Tests\Feature\ProdutoTest::um_produto_pode_ser_criado
Symfony\Component\HttpKernel\Exception\NotFoundHttpException: POST http://tdd.vm/produtos

/home/vagrant/tdd/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/InteractsWithExceptionHandling.php:127
/home/vagrant/tdd/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:426
/home/vagrant/tdd/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:114
/home/vagrant/tdd/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php:510
/home/vagrant/tdd/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php:322
/home/vagrant/tdd/tests/Feature/ProdutoTest.php:31</error>
        </testcase>
      </testsuite>
    </testsuite>
  </testsuite>
</testsuites>
